# Generated by Django 2.1.2 on 2018-12-16 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='tx',
            new_name='name',
        ),
    ]
