# Generated by Django 2.1.2 on 2018-12-16 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='category',
            field=models.CharField(default='stołówka', max_length=255),
            preserve_default=False,
        ),
    ]
