# Generated by Django 2.1.2 on 2018-12-16 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_restaurant_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='category',
        ),
    ]
