# Generated by Django 2.1.2 on 2018-12-17 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_auto_20181216_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(default='slug', max_length=200),
            preserve_default=False,
        ),
    ]
