# Generated by Django 2.1.2 on 2018-12-17 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_restaurant_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='slug',
        ),
    ]
