# Generated by Django 2.1.2 on 2018-12-17 13:56

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_restaurant_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='adress',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='author',
            field=models.CharField(default='', max_length=255,null=True),
            preserve_default=False,
        ),
    ]
