# Generated by Django 2.1.2 on 2018-12-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_auto_20181217_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='author',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
