# Generated by Django 2.1.2 on 2018-12-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_auto_20181217_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_opening', models.TimeField(blank=True, null=True)),
                ('monady_closing', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='opening_hours',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='price',
            field=models.IntegerField(blank=True, choices=[(1, 'tanio'), (2, 'drozej'), (3, 'Wednesday')], null=True),
        ),
    ]
