# Generated by Django 2.1.2 on 2018-12-17 21:04

from django.db import migrations, models
import restaurants.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_auto_20181217_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='opening_hours',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='price',
            field=models.CharField(blank=True, choices=[(restaurants.models.PriceChoice('TANIO'), 'TANIO'), (restaurants.models.PriceChoice('UMIARKOWANIE'), 'UMIARKOWANIE'), (restaurants.models.PriceChoice('DROGO'), 'DROGO')], max_length=5, null=True),
        ),
    ]
