# Generated by Django 2.1.2 on 2018-12-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0013_auto_20181218_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='price',
            field=models.IntegerField(blank=True, choices=[(1, 'tanio'), (2, 'przystępnie'), (3, 'drogo')], null=True),
        ),
    ]
