# Generated by Django 2.1.2 on 2018-12-18 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0014_auto_20181218_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hours',
            old_name='monady_closing',
            new_name='closing_time',
        ),
        migrations.RenameField(
            model_name='hours',
            old_name='monday_opening',
            new_name='opening_time',
        ),
        migrations.AddField(
            model_name='hours',
            name='day',
            field=models.IntegerField(choices=[(1, 'poniedziałek'), (2, 'wtorek'), (3, 'środa'), (4, 'czwartek'), (5, 'piątek'), (6, 'sobota'), (7, 'niedziela')], default=1),
        ),
        migrations.AddField(
            model_name='hours',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.Restaurant'),
        ),
    ]
