# Generated by Django 2.1.2 on 2018-12-18 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0015_auto_20181218_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='adress',
            new_name='address',
        ),
    ]
