# Generated by Django 2.1.2 on 2018-12-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0016_auto_20181218_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='aaa', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
