# Generated by Django 2.1.2 on 2018-12-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0018_auto_20181218_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='created',
            field=models.DateTimeField(editable=False),
        ),
    ]
