# Generated by Django 2.1.2 on 2018-12-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0019_auto_20181218_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='closing_hours',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
