# Generated by Django 2.1.2 on 2019-01-14 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0024_restaurant_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('score', models.IntegerField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='rating',
            new_name='rate',
        ),
        migrations.AddField(
            model_name='rating',
            name='resturant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.Restaurant'),
        ),
    ]
