# Generated by Django 2.1.2 on 2019-01-14 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0026_auto_20190114_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='resturant',
            new_name='restaurant',
        ),
    ]
