# Generated by Django 2.1.2 on 2019-01-14 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0028_inforating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inforating',
            name='rate',
            field=models.IntegerField(null=True),
        ),
    ]
