# Generated by Django 2.1.2 on 2019-01-14 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0029_auto_20190114_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='infoRate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
