# Generated by Django 2.1.2 on 2019-01-17 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0037_auto_20190117_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='category',
        ),
    ]
