# Generated by Django 2.1.2 on 2019-01-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0038_remove_restaurant_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hours',
            name='restaurant',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='Hours',
        ),
    ]
